### ISSUE TITLE
Unable to parse SmokeTestReport for 

### ISSUE THREAD

**Issue by vivienneChen** [jenkinsci/seleniumhtmlreport#5]
I use htmltestrunnder to run selenium project wirtten by python, and generate html report SmokeTestReport.html, but when  publishing selenium html report on jenkins, it always fails a with java.lang.NumberFormatException.

----generate SmokeTestReport.html in my code.
   dir = os.getcwd()
    outfile = open(dir + "/SmokeTestReport.html", "w")
    testRunner = HTMLTestRunner.HTMLTestRunner(stream=outfile, title='test-reports', description='Smoke Tests')

configurate in jenkins
	Selenium tests results location: {current project folder}

below is jenkins console log:
******************************************
Started by user
Building in workspace /root/.jenkins/jobs/Test_Report/workspace
[workspace] $ /bin/sh -xe /tmp/hudson9186170553294660404.sh
+ pwd
/root/.jenkins/jobs/Test_Report/workspace
+ cd /root/.jenkins/jobs/Test_Report/workspace/NewDashboard
+ python runTest.py XXX
....
Time Elapsed: 0:00:03.792874
Publishing Selenium report...
Copying the reports.
parsing resultFile SmokeTestReport.html
Unable to parse SmokeTestReport.html: java.lang.NumberFormatException: null
Finished: SUCCESS

**Comment by sisao** [comment]
Hi,
from the output ("java.lang.NumberFormatException: null") you can see that one of the fields in the html report is not filled.
Maybe you can take a look in the SmokeTestReport.html file and find out which it is.
Perhaps then I can figure out what is causing the error.

**Comment by vivienneChen** [comment]
The report  is generated by HTMLTestRunner.  I can send the SmokeTestReport.html file to you, could you help have a look?

[SmokeTestReport.html.zip](https://github.com/jenkinsci/seleniumhtmlreport/files/85277/SmokeTestReport.html.zip)

**Comment by sisao** [comment]
Your attached file links to 404...

**Comment by vivienneChen** [comment]
sorry, i did not test it.
[SmokeTestReport.html.zip](https://github.com/jenkinsci/seleniumhtmlreport/files/86696/SmokeTestReport.html.zip)

**Comment by sisao** [comment]
Your html file seems like a result of HTMLTestRunner and not result of Selenium. This plugin can only parse Selenium result files. 
Do you really need to use this plugin because your SmokeTestReport.html is already a nice formatted test result visualization.

**Comment by vivienneChen** [comment]
Thanks for your reply.  HTMLTestRunner is nice formatted, i can even publish it to job level, but it cannot reflect the test result status to jenkins, jobs is always passed.
I have also tried xmltestrunner using junit test result pulish plugins, but it cannot reflect the run status correctly.

i am using python and selenium to automate web testing, do you have a good way to generate the SELENIUM RESULT FILES that can parse to jenkins? 

Thanks in advance@
